export const ALL_ACCOUNT_HOLDERS = 'ALL_ACCOUNT_HOLDERS';
export const SINGLE_ACCOUNT = 'SINGLE_ACCOUNT';
export const MAKE_TRANSACTION = 'TRANSACTION';
export const ALL_TRANSACTION = 'ALL_TRANSACTION';